/**
 * certificate.model.js
 *
 * Direct database access for the `certificates` table, plus the
 * transactional issuance flow that couples the applications.status
 * flip ('approved' -> 'certificate_issued') with the certificate row
 * insert so the two can never diverge (e.g. a status change without
 * a corresponding certificate, or vice versa).
 */

const { query, getClient } = require('../config/db.config');

async function findByApplicationId(applicationId) {
  const result = await query(
    `SELECT id, application_id, certificate_number, file_path, qr_code_value, status, issued_by, issued_at, revoked_at
     FROM certificates
     WHERE application_id = $1`,
    [applicationId]
  );
  return result.rows[0] || null;
}

/**
 * Fetch a certificate by id, joined with its application and the
 * applicant's public profile fields. Used by both the (authenticated)
 * download endpoint and the (public) verification endpoint — callers
 * decide which returned fields are safe to expose in each context.
 */
async function findByIdWithApplication(certificateId) {
  const result = await query(
    `SELECT c.id, c.application_id, c.certificate_number, c.file_path, c.qr_code_value,
            c.status, c.issued_by, c.issued_at, c.revoked_at,
            a.applicant_id, a.purpose, a.status AS application_status,
            u.full_name AS applicant_name
     FROM certificates c
     JOIN applications a ON a.id = c.application_id
     JOIN users u ON u.id = a.applicant_id
     WHERE c.id = $1`,
    [certificateId]
  );
  return result.rows[0] || null;
}

/**
 * Atomically: (1) flip the application to 'certificate_issued' only if
 * it is currently 'approved', and (2) insert the certificate row —
 * both in a single DB transaction. If step 1 affects zero rows (the
 * application was already issued, or moved out of 'approved' by a
 * concurrent request), the transaction rolls back and the caller gets
 * `{ application: null, certificate: null }` — no orphaned PDF
 * reference and no orphaned status change.
 *
 * The certificate id is generated by the caller (not the DB default)
 * so the verification URL / QR code can be built and the PDF written
 * to disk *before* this transaction runs, using a stable, final id.
 */
async function issueWithTransaction({ applicationId, certificateId, certificateNumber, filePath, qrCodeValue, issuedBy }) {
  const client = await getClient();
  try {
    await client.query('BEGIN');

    const appResult = await client.query(
      `UPDATE applications
       SET status = 'certificate_issued'
       WHERE id = $1 AND status = 'approved'
       RETURNING id, applicant_id, purpose, status, rejection_reason, submitted_at, reviewed_at, created_at, updated_at`,
      [applicationId]
    );

    if (appResult.rowCount === 0) {
      await client.query('ROLLBACK');
      return { application: null, certificate: null };
    }

    const certResult = await client.query(
      `INSERT INTO certificates (id, application_id, certificate_number, file_path, qr_code_value, issued_by)
       VALUES ($1, $2, $3, $4, $5, $6)
       RETURNING id, application_id, certificate_number, file_path, qr_code_value, status, issued_by, issued_at, revoked_at`,
      [certificateId, applicationId, certificateNumber, filePath, qrCodeValue, issuedBy]
    );

    await client.query('COMMIT');
    return { application: appResult.rows[0], certificate: certResult.rows[0] };
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

module.exports = { findByApplicationId, findByIdWithApplication, issueWithTransaction };
